# Generated by Django 4.2.2 on 2023-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=256, null=True)),
                ('image_url', models.URLField(default='', null=True)),
            ],
        ),
    ]
