# Generated by Django 4.2.2 on 2023-07-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_user_id_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=0, primary_key=True, serialize=False),
        ),
    ]
